# Generated by Django 5.1.15 on 2026-02-27 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = system default, set = tenant override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(help_text='Supports {{PLACEHOLDER}} syntax.', max_length=500)),
                ('body_html', models.TextField(help_text='HTML body with {{PLACEHOLDER}} syntax.')),
                ('body_text', models.TextField(blank=True, help_text='Plain-text fallback.')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of expected variable names (documentation only).')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = system default, set = tenant override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Shared variables for all steps.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='emails.emailsequence')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_enrollments', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_slug', models.CharField(help_text='Denormalized for audit.', max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(help_text='Rendered subject.', max_length=500)),
                ('body_html', models.TextField(help_text='Rendered HTML body.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Variables used for rendering.')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('tracking_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='tenants.tenant')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.emailtemplate')),
                ('sequence_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='emails.sequenceenrollment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('delay_days', models.PositiveIntegerField(default=0)),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='emails.emailsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_steps', to='emails.emailtemplate')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='emailsequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_email_sequence_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='emailsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_system_email_sequence_slug'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_email_template_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='emailtemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_system_email_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='sequenceenrollment',
            constraint=models.UniqueConstraint(fields=('tenant', 'sequence', 'recipient_email'), name='unique_enrollment_per_recipient'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.UniqueConstraint(fields=('sequence', 'position'), name='unique_step_position_per_sequence'),
        ),
    ]
