# Generated by Django 5.1.15 on 2026-03-01 13:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_type', models.CharField(choices=[('smtp', 'SMTP'), ('sendgrid', 'SendGrid')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password_encrypted', models.TextField(blank=True, help_text='Fernet-encrypted SMTP password.')),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('sendgrid_api_key_encrypted', models.TextField(blank=True, help_text='Fernet-encrypted SendGrid API key.')),
                ('from_email', models.EmailField(help_text='Absender-Email-Adresse.', max_length=254)),
                ('from_name', models.CharField(blank=True, help_text='Absender-Anzeigename.', max_length=255)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('last_test_message', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider_type'), name='unique_email_provider_per_tenant'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_email_provider_per_tenant')],
            },
        ),
    ]
