# Generated by Django 5.1.15 on 2026-03-05 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_convert_health_score_scale'),
        ('emails', '0003_emailproviderconnection_inbound_parse_domain_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wa_message_id', models.CharField(blank=True, help_text='Meta Message ID (wamid.xxx).', max_length=255, null=True, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Eingehend'), ('outbound', 'Ausgehend')], max_length=10)),
                ('from_number', models.CharField(max_length=20)),
                ('to_number', models.CharField(max_length=20)),
                ('body_text', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Bild'), ('document', 'Dokument'), ('audio', 'Audio'), ('video', 'Video'), ('template', 'Template')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Empfangen'), ('sent', 'Gesendet'), ('delivered', 'Zugestellt'), ('read', 'Gelesen'), ('failed', 'Fehlgeschlagen')], default='received', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Raw-Webhook-Payload oder zusaetzliche Daten.')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
