# Generated by Django 5.1.15 on 2026-02-28 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = system sequence, set = tenant-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_sequences', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('endpoint', models.CharField(help_text='Jira REST path, z.B. /rest/api/3/project. Supports {{PLACEHOLDER}}.', max_length=500)),
                ('body_json', models.JSONField(blank=True, default=dict, help_text='Request body with {{PLACEHOLDER}} syntax.')),
                ('headers_json', models.JSONField(blank=True, default=dict, help_text='Extra headers (merged with auth headers).')),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of expected variable names.')),
                ('output_mapping', models.JSONField(blank=True, default=dict, help_text='JSON path → variable name for extracting response values.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be edited by tenants.')),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = system template, set = tenant-specific.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('input_context', models.JSONField(blank=True, default=dict, help_text='Input variables for the execution.')),
                ('accumulated_context', models.JSONField(blank=True, default=dict, help_text='Accumulated outputs from completed steps (for forwarding between steps).')),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, help_text="Cross-ref type, z.B. 'client'.", max_length=100)),
                ('entity_id', models.CharField(blank=True, help_text='Cross-ref ID, z.B. client UUID.', max_length=255)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_executions', to=settings.AUTH_USER_MODEL)),
                ('sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='integrations.actionsequence')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='integrations.actiontemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Jira Cloud', max_length=255)),
                ('jira_url', models.URLField(help_text='z.B. https://firma.atlassian.net')),
                ('jira_email', models.EmailField(help_text='Jira-Account-Email fuer API-Zugriff.', max_length=254)),
                ('jira_api_token_encrypted', models.TextField(help_text='Fernet-encrypted API token.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Delay before executing this step.')),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='integrations.actionsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_steps', to='integrations.actiontemplate')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StepLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('response_headers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('extracted_outputs', models.JSONField(blank=True, default=dict, help_text='Values extracted via output_mapping.')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='integrations.actionexecution')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_logs', to='integrations.actiontemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='actionsequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_action_sequence_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='actionsequence',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_system_action_sequence_slug'),
        ),
        migrations.AddConstraint(
            model_name='actiontemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_action_template_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='actiontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_system_action_template_slug'),
        ),
        migrations.AddConstraint(
            model_name='jiraconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_jira_connection_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='sequencestep',
            constraint=models.UniqueConstraint(fields=('sequence', 'position'), name='unique_integration_step_position'),
        ),
    ]
