# Generated by Django 5.1.15 on 2026-03-01 18:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_tenant_integration_client_data'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwilioConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='Twilio Telefonie', max_length=255)),
                ('account_sid', models.CharField(help_text='Twilio Account SID (beginnt mit AC).', max_length=100, validators=[django.core.validators.RegexValidator('^AC[a-f0-9]{32}$', "Account SID muss mit 'AC' beginnen.")])),
                ('auth_token_encrypted', models.TextField(help_text='Fernet-encrypted Auth Token.')),
                ('twiml_app_sid', models.CharField(help_text='TwiML App SID (beginnt mit AP).', max_length=100, validators=[django.core.validators.RegexValidator('^AP[a-f0-9]{32}$', "TwiML App SID muss mit 'AP' beginnen.")])),
                ('phone_number', models.CharField(help_text='Twilio-Telefonnummer im E.164-Format.', max_length=20, validators=[django.core.validators.RegexValidator('^\\+[1-9]\\d{1,14}$', 'Telefonnummer muss im E.164-Format sein (z.B. +4930123456).')])),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_twilio_connection_per_tenant')],
            },
        ),
    ]
