# Generated by Django 5.1.15 on 2026-03-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_twilioconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Mandantenspezifische Jira-Konfiguration (Schema-IDs, Custom-Field-IDs etc.)'),
        ),
    ]
