# Generated by Django 5.1.15 on 2026-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_jiraconnection_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontemplate',
            name='auth_credentials_encrypted',
            field=models.TextField(blank=True, help_text='Fernet-verschluesselte JSON-Credentials je nach auth_type.'),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='auth_type',
            field=models.CharField(choices=[('none', 'Keine'), ('bearer', 'Bearer Token'), ('basic', 'Basic Auth'), ('api_key', 'API Key')], default='none', help_text='Auth-Typ fuer Webhooks. Jira nutzt die JiraConnection.', max_length=20),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='target_type',
            field=models.CharField(choices=[('jira', 'Jira'), ('webhook', 'Webhook')], default='jira', help_text='Zieltyp: Jira (ueber JiraConnection) oder Webhook (eigene URL).', max_length=20),
        ),
        migrations.AddField(
            model_name='actiontemplate',
            name='webhook_url',
            field=models.CharField(blank=True, help_text='Volle URL fuer Webhooks, z.B. https://api.example.com/hook. Supports {{PLACEHOLDER}}.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='endpoint',
            field=models.CharField(blank=True, help_text='Jira REST path, z.B. /rest/api/3/project. Supports {{PLACEHOLDER}}.', max_length=500),
        ),
    ]
