# Generated by Django 5.1.15 on 2026-03-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_actiontemplate_auth_credentials_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantintegration',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Integrationsspezifische Konfiguration (z.B. confluence_parent_page_id).'),
        ),
    ]
