# Generated by Django 5.1.15 on 2026-03-05 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_add_config_to_tenantintegration'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(default='WhatsApp Business', max_length=255)),
                ('phone_number_id', models.CharField(help_text='Meta Phone Number ID (aus dem WhatsApp Business Dashboard).', max_length=100)),
                ('business_account_id', models.CharField(help_text='WhatsApp Business Account ID (WABA ID).', max_length=100)),
                ('access_token_encrypted', models.TextField(help_text='Fernet-encrypted Meta Access Token.')),
                ('webhook_verify_token', models.CharField(help_text='Verify-Token fuer Meta Webhook-Verifikation.', max_length=255)),
                ('display_phone_number', models.CharField(help_text='Anzeige-Nummer im E.164-Format, z.B. +4915112345678.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_success', models.BooleanField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant',), name='unique_active_whatsapp_connection_per_tenant')],
            },
        ),
    ]
