# Generated by Django 5.1.15 on 2026-03-02 20:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0006_add_clientkeyfact'),
        ('emails', '0002_emailproviderconnection'),
        ('tasks', '0007_recurringtaskschedule_recurringtaskrun_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NPSCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('day_offset', 'Tag nach Start'), ('quarterly', 'Quartalsweise'), ('manual', 'Manuell')], default='day_offset', max_length=20)),
                ('day_offset', models.PositiveIntegerField(default=90, help_text='Tage nach Client start_date.')),
                ('repeat_interval_days', models.PositiveIntegerField(default=90, help_text='0 = einmalig, >0 = Wiederholung alle X Tage.')),
                ('is_active', models.BooleanField(default=True)),
                ('email_template', models.ForeignKey(blank=True, help_text='Template mit {{NPS_URL}} Placeholder.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_campaigns', to='emails.emailtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPSSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('responded', 'Beantwortet'), ('expired', 'Abgelaufen')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='nps.npscampaign')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_surveys', to='clients.client')),
                ('email_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_surveys', to='emails.emaillog')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nps_surveys', to='tasks.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NPSResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('segment', models.CharField(choices=[('promoter', 'Promoter'), ('passive', 'Passive'), ('detractor', 'Detractor')], editable=False, max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nps_responses', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='nps.npssurvey')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestimonialRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('google_review', 'Google-Bewertung'), ('video', 'Video-Testimonial'), ('written', 'Schriftlich'), ('draft_approve', 'Entwurf zur Freigabe')], default='written', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Angefragt'), ('accepted', 'Zugesagt'), ('received', 'Erhalten'), ('published', 'Veroeffentlicht'), ('declined', 'Abgelehnt')], default='requested', max_length=20)),
                ('content', models.TextField(blank=True, default='', help_text='Testimonial-Text.')),
                ('platform_url', models.URLField(blank=True, default='', help_text='Link zur Bewertung.')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_requests', to='clients.client')),
                ('nps_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_requests', to='nps.npsresponse')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_requests', to='tasks.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='npscampaign',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_nps_campaign_slug_per_tenant'),
        ),
    ]
