# Generated by Django 5.1.15 on 2026-03-01 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_remove_service_notes'),
        ('emails', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('email', 'E-Mail'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('manual', 'Manuell')], default='manual', max_length=20)),
                ('phase', models.PositiveSmallIntegerField(default=0)),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('completed', 'Erledigt'), ('skipped', 'Uebersprungen')], default='open', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.client')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_tasks', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='emails.emailtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['phase', 'due_date', '-priority', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('comment', 'Kommentar'), ('task_created', 'Aufgabe erstellt'), ('task_completed', 'Aufgabe erledigt'), ('task_skipped', 'Aufgabe uebersprungen'), ('status_changed', 'Status geaendert'), ('email_sent', 'E-Mail gesendet')], max_length=30)),
                ('content', models.TextField(blank=True, default='', help_text='Kommentartext oder automatische Beschreibung.')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_activities', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='clients.client')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tasks.task')),
            ],
            options={
                'verbose_name_plural': 'Client activities',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('email', 'E-Mail'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('manual', 'Manuell')], default='manual', max_length=20)),
                ('phase', models.PositiveSmallIntegerField(default=0, help_text='After-Sales Phase (0-11).')),
                ('day_offset', models.IntegerField(default=0, help_text='Tage nach Client-Startdatum fuer die Faelligkeit.')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch'), ('critical', 'Kritisch')], default='medium', max_length=20)),
                ('default_subtasks', models.JSONField(blank=True, default=list, help_text='Liste von Subtask-Titeln, z.B. ["Adresse pruefen", "Paket packen"].')),
                ('is_active', models.BooleanField(default=True)),
                ('email_template', models.ForeignKey(blank=True, help_text='Verknuepfte E-Mail-Vorlage (nur fuer action_type=email).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='emails.emailtemplate')),
                ('tenant', models.ForeignKey(blank=True, help_text='NULL = System-Template, gesetzt = mandantenspezifisch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='tenants.tenant')),
            ],
            options={
                'ordering': ['phase', 'day_offset', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_instances', to='tasks.tasktemplate'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_task_template_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='tasktemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', True)), fields=('slug',), name='unique_system_task_template_slug'),
        ),
    ]
