# Generated by Django 5.1.15 on 2026-03-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
        ('integrations', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='action_sequence',
            field=models.ForeignKey(blank=True, help_text='Jira-Sequenz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='integrations.actionsequence'),
        ),
        migrations.AddField(
            model_name='task',
            name='action_template',
            field=models.ForeignKey(blank=True, help_text='Einzelne Jira-Aktion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='integrations.actiontemplate'),
        ),
        migrations.AddField(
            model_name='task',
            name='email_templates',
            field=models.ManyToManyField(blank=True, help_text='Verfuegbare E-Mail-Vorlagen fuer diese Aufgabe.', related_name='tasks_m2m', to='emails.emailtemplate'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='action_sequence',
            field=models.ForeignKey(blank=True, help_text='Jira-Sequenz mit mehreren API-Calls (nur fuer action_type=jira_*).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='integrations.actionsequence'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='action_template',
            field=models.ForeignKey(blank=True, help_text='Einzelne Jira-Aktion (nur fuer action_type=jira_*).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='integrations.actiontemplate'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='email_templates',
            field=models.ManyToManyField(blank=True, help_text='Verfuegbare E-Mail-Vorlagen fuer diese Aufgabe.', related_name='task_templates_m2m', to='emails.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='clientactivity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Kommentar'), ('task_created', 'Aufgabe erstellt'), ('task_completed', 'Aufgabe erledigt'), ('task_skipped', 'Aufgabe uebersprungen'), ('status_changed', 'Status geaendert'), ('email_sent', 'E-Mail gesendet'), ('jira_executed', 'Jira-Aktion ausgefuehrt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Verknuepfte E-Mail-Vorlage (Legacy, nicht mehr im Frontend genutzt).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates', to='emails.emailtemplate'),
        ),
    ]
