# Generated by Django 5.1.15 on 2026-03-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_service_notes'),
        ('tasks', '0003_tasklist_tasklistitem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklistitem',
            options={'ordering': ['group_position', 'position']},
        ),
        migrations.AddField(
            model_name='task',
            name='group_label',
            field=models.CharField(blank=True, default='', help_text='Gruppenname aus der Aufgabenliste, z.B. "Setup & Vorbereitung".', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='source_list',
            field=models.ForeignKey(blank=True, help_text='Aufgabenliste, aus der diese Aufgabe generiert wurde.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_tasks', to='tasks.tasklist'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='default_for_service_type',
            field=models.ForeignKey(blank=True, help_text='Wenn gesetzt, wird diese Liste als Standard fuer diesen Service-Typ empfohlen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_task_lists', to='clients.servicetype'),
        ),
        migrations.AddField(
            model_name='tasklistitem',
            name='day_offset',
            field=models.IntegerField(blank=True, help_text='Ueberschreibt den Tag-Offset des Templates.', null=True),
        ),
        migrations.AddField(
            model_name='tasklistitem',
            name='group_label',
            field=models.CharField(blank=True, default='', help_text='Gruppenname in der Liste, z.B. "Setup", "Woche 1".', max_length=100),
        ),
        migrations.AddField(
            model_name='tasklistitem',
            name='group_position',
            field=models.PositiveIntegerField(default=0, help_text='Sortierung der Gruppen innerhalb der Liste.'),
        ),
    ]
