# Generated by Django 5.1.15 on 2026-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_group_fields_and_source_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Kommentar'), ('task_created', 'Aufgabe erstellt'), ('task_completed', 'Aufgabe erledigt'), ('task_skipped', 'Aufgabe uebersprungen'), ('status_changed', 'Status geaendert'), ('email_sent', 'E-Mail gesendet'), ('jira_executed', 'Jira-Aktion ausgefuehrt'), ('webhook_executed', 'Webhook ausgefuehrt')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
    ]
