# Generated by Django 5.1.15 on 2026-03-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailproviderconnection'),
        ('tasks', '0005_alter_clientactivity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='email_sequence',
            field=models.ForeignKey(blank=True, help_text='E-Mail-Sequenz.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_email_seq', to='emails.emailsequence'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='email_sequence',
            field=models.ForeignKey(blank=True, help_text='E-Mail-Sequenz (nur fuer action_type=email_sequence).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_templates_email_seq', to='emails.emailsequence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('email_sequence', 'E-Mail-Sequenz'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('email_sequence', 'E-Mail-Sequenz'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
    ]
