# Generated by Django 5.1.15 on 2026-03-02 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models

from apps.common.db.rls import EnableRLS


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_add_clientkeyfact'),
        ('tasks', '0006_task_email_sequence_tasktemplate_email_sequence_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTaskSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.CharField(choices=[('weekly', 'Woechentlich'), ('biweekly', 'Alle 2 Wochen'), ('monthly', 'Monatlich'), ('quarterly', 'Quartalsweise')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('client_scope', models.CharField(choices=[('all_active', 'Alle aktiven Clients'), ('by_service_type', 'Nach Service-Typ'), ('explicit', 'Explizite Auswahl')], default='all_active', max_length=20)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clients', models.ManyToManyField(blank=True, help_text='Nur bei client_scope=explicit.', related_name='recurring_schedules', to='clients.client')),
                ('service_types', models.ManyToManyField(blank=True, help_text='Nur bei client_scope=by_service_type.', related_name='recurring_schedules', to='clients.servicetype')),
                ('task_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_schedules', to='tasks.tasklist')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringTaskRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('success', 'Erfolgreich'), ('partial', 'Teilweise'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Uebersprungen')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('clients_processed', models.PositiveIntegerField(default=0)),
                ('tasks_created', models.PositiveIntegerField(default=0)),
                ('tasks_skipped', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenants.tenant')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='tasks.recurringtaskschedule')),
            ],
            options={
                'ordering': ['-started_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='recurringtaskschedule',
            index=models.Index(fields=['is_active', 'next_run_at'], name='idx_schedule_active_next_run'),
        ),
        migrations.AddConstraint(
            model_name='recurringtaskschedule',
            constraint=models.UniqueConstraint(fields=('tenant', 'task_list'), name='unique_schedule_per_list_per_tenant'),
        ),
        EnableRLS('tasks_recurringtaskschedule'),
        EnableRLS('tasks_recurringtaskrun'),
    ]
