# Generated by Django 5.1.15 on 2026-03-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_recurringtaskschedule_recurringtaskrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Kommentar'), ('task_created', 'Aufgabe erstellt'), ('task_completed', 'Aufgabe erledigt'), ('task_skipped', 'Aufgabe uebersprungen'), ('status_changed', 'Status geaendert'), ('email_sent', 'E-Mail gesendet'), ('jira_executed', 'Jira-Aktion ausgefuehrt'), ('webhook_executed', 'Webhook ausgefuehrt'), ('nps_sent', 'NPS-Umfrage gesendet'), ('nps_received', 'NPS erhalten')], max_length=30),
        ),
    ]
