# Generated by Django 5.1.15 on 2026-03-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_clientactivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_trigger_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='auto_trigger_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='trigger_mode',
            field=models.CharField(blank=True, choices=[('manual', 'Manuell'), ('auto_on_due', 'Automatisch bei Fälligkeit')], help_text='NULL = Template-Default verwenden.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='trigger_mode',
            field=models.CharField(choices=[('manual', 'Manuell'), ('auto_on_due', 'Automatisch bei Fälligkeit')], default='manual', max_length=20),
        ),
    ]
