# Generated by Django 5.1.15 on 2026-03-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_trigger_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('open', 'Offen'), ('in_progress', 'In Bearbeitung'), ('completed', 'Erledigt'), ('skipped', 'Uebersprungen')], default='open', max_length=20),
        ),
    ]
