# Generated by Django 5.1.15 on 2026-03-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_add_planned_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientactivity',
            name='activity_type',
            field=models.CharField(choices=[('comment', 'Kommentar'), ('task_created', 'Aufgabe erstellt'), ('task_completed', 'Aufgabe erledigt'), ('task_skipped', 'Aufgabe uebersprungen'), ('status_changed', 'Status geaendert'), ('email_sent', 'E-Mail gesendet'), ('jira_executed', 'Jira-Aktion ausgefuehrt'), ('webhook_executed', 'Webhook ausgefuehrt'), ('nps_sent', 'NPS-Umfrage gesendet'), ('nps_received', 'NPS erhalten'), ('auto_trigger_success', 'Auto-Trigger erfolgreich'), ('auto_trigger_failed', 'Auto-Trigger fehlgeschlagen'), ('list_removed', 'Aufgabenliste entfernt'), ('health_check_completed', 'Health-Check ausgefuellt'), ('churn_check_completed', 'Churn-Check ausgefuellt'), ('whatsapp_sent', 'WhatsApp gesendet')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('email_sequence', 'E-Mail-Sequenz'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('health_check', 'Health-Check'), ('churn_check', 'Churn-Check'), ('whatsapp', 'WhatsApp'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasktemplate',
            name='action_type',
            field=models.CharField(choices=[('email', 'E-Mail'), ('email_sequence', 'E-Mail-Sequenz'), ('package', 'Paket'), ('phone', 'Telefonat'), ('meeting', 'Meeting'), ('document', 'Dokument'), ('jira_project', 'Jira-Projekt'), ('jira_ticket', 'Jira-Ticket'), ('webhook', 'Webhook'), ('health_check', 'Health-Check'), ('churn_check', 'Churn-Check'), ('whatsapp', 'WhatsApp'), ('manual', 'Manuell')], default='manual', max_length=20),
        ),
    ]
