# Generated by Django 5.1.15 on 2026-02-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cloud_storage_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
