# Generated by Django 5.1.15 on 2026-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_cloud_storage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
