# Generated by Django 5.1.15 on 2026-02-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_service_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='end_date',
        ),
    ]
