# Generated by Django 5.1.15 on 2026-02-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='notes',
        ),
    ]
